services:
  - type: web
    name: n8n
    env: docker
    plan: free
    autoDeploy: true
    dockerCommand: "n8n start"
    envVars:
      - key: N8N_PORT
        value: 5678
      - key: N8N_HOST
        value: 0.0.0.0
      - key: WEBHOOK_URL
        value: https://n8n.onrender.com
